run:
  skip-dirs:
    - "vendor"
  timeout: 2m

linters:
  enable:
    - govet
    - gofmt
    - staticcheck
    - errcheck
    - revive
    - unused
    - gosimple
    - gocritic
    - ineffassign
    - typecheck

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
