version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-export-go
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./exports:/app/exports
    depends_on:
      - rabbitmq
    networks:
      - appnet
    ports:
      - "8002:8002"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
